services: 
  frontend:
    container_name: react-frontend
    build:
      dockerfile: Dockerfile
    ports:
      - "5173:80"           # локально будет доступно на порту 5173
    restart: unless-stopped